<?php
use yii\bootstrap\Collapse;

?>
<!-- site/_help_faq.php -->

<h1>FAQs</h1>

<?php

echo Collapse::widget([
    'items' => [
        // equivalent to the above
        [
            'label' => 'What is the Exertis Digital Stock Room (EDSR)?',
            'content' => 'In much the same way as books and music are being delivered '
            . 'via downloads, so too is the latest software. '
            . 'When you buy digital products, like software, from Exertis, '
            . 'we will no longer deliver physical products, but instead we will '
            . 'deliver license keys using EDSR. Think of EDSR as your own Digital '
            . 'Stock Room. Only you have they keys to open it, and when you walk '
            . 'inside you will see all the digital products you have ordered on the shelves.',
            // open its content by default
            //'contentOptions' => ['class' => 'in']
        ],

        [
            'label' => 'Is EDSR secure?',
            'content' => 'We have gone to great lengths to protect your \'stock\'. After all,'
            . 'once we have delivered your digital product, it is owned by you. '
            . 'EDSR acts as a secure storage area holding your stock.'
//            . 'We use the latest Two Factor Authentication systems which means that '
//            . 'even if someone discovers your email address and password, they need '
//            . 'and extra code which is generated by your mobile phone - and that '
//            . 'code changes every 30 seconds.',
            //'contentOptions' => [...],
            //'options' => [...],
        ],
/*
        [
            'label' => 'What are Two Factor Authentication and One Time Passwords?',
            'content' => 'Two Factor Authentication (2FA) and One Time Passwords '
            . '(OTP) are a way of making logging into a system even more secure '
            . 'than using just username/password. YOU might be familiar with these'
            . 'if you use online banking. Having an extra password that '
            . 'changes every 30 seconds, and cannot be remembered or shared makes EDSR'
            . 'extremely secure so that only you can access <em>your</em> stock in <em>your</em> stockroom.'
            //'contentOptions' => [...],
            //'options' => [...],
        ],
*/
        [
            'label' => 'How will I know that my digital products are ready?',
            'content' => 'New EDSR users will be notified by email and taken through '
            . 'a simple signup process, which includes up your password.'
            . 'Established users will be notified by email whene stock is delivered into your Digital Stock Room.'
            //'contentOptions' => [...],
            //'options' => [...],
        ],

        [
            'label' => 'Does EDSR change the way I place my orders?',
            'content' => 'No, you can still place your orders via telephone, email, '
            . 'our websites, EDI, or even on this platform. EDSR is a new way of delivering digital products.'
        ],

        [
            'label' => 'When can I get my License keys for products I have ordered?',
            'content' => 'Your order goes through the normal process within Exertis, so'
            . 'your digital purchases will not appear instantly in your storeroom. Delivery may take up to 2 hours, but will often be quicker, often within 15 minutes.'
            //'contentOptions' => [...],
            //'options' => [...],
        ],
        [
            'label' => 'Can I return digital products or cancel my order?',
            'content' => 'No, sorry, once your order is placed, digital products cannot be returned or refunded, or orders cancelled.'
            //'contentOptions' => [...],
            //'options' => [...],
        ],

        [
            'label' => 'I have a Microsoft Office 2016 Key - how do I use it?',
            'content' => 'Please visit <a href="https://officesetup.getmicrosoftkey.com/" target="_blank">https://officesetup.getmicrosoftkey.com/</a> and enter your key to download your software.'
            //'contentOptions' => [...],
            //'options' => [...],
        ],

        [
            'label' => 'I have a Microsoft Office 365 Key - how do I use it?',
            'content' => 'Please login to <a href="http://office.com/myaccount" target="_blank">http://office.com/myaccount</a> and click Install.'
            //'contentOptions' => [...],
            //'options' => [...],
        ],

        [
            'label' => 'I have a Microsoft Office Mac Key - how do I use it?',
            'content' => 'Please visit <a href="http://www.microsoft.com/mac/office-2011-digital-download" target="_blank">http://www.microsoft.com/mac/office-2011-digital-download</a> to download your software.'
            //'contentOptions' => [...],
            //'options' => [...], 
        ],
        [
            'label' => 'I have a Microsoft Windows 10 Key - how do I use it?',
            'content' => 'Please visit <a href="https://www.microsoft.com/en-us/software-download/windows10" target="_blank">https://www.microsoft.com/en-us/software-download/windows10</a> to download your software.'
            //'contentOptions' => [...],
            //'options' => [...],
        ],
        [
            'label' => 'I have a McAfee Key - how do I use it?',
            'content' => 'Please visit <a href="https://secure.mcafee.com/apps/downloads/my-products/login.aspx?region=uk" target="_blank">https://secure.mcafee.com/apps/downloads/my-products/login.aspx?region=uk</a> to download your software.'
            //'contentOptions' => [...],
            //'options' => [...],
        ],
        [
            'label' => 'I\'m having problems using my Microsoft Key.',
            'content' => 'Please call Microsoft on 0344 800 2400'
            //'contentOptions' => [...],
            //'options' => [...],
        ],
        [
            'label' => 'Xbox Gift Card Pricing.',
            'content' => '<p>Xbox Gift Cards are now sold through an "Agency Model". '
            . 'This means that the distributor and reseller never "owns" the product. '
            . 'The product is sold to the end consumer directly by Microsoft and you, '
            . 'the reseller, receive and Agency Fee for handling the transaction.</p> '
            . 'Exertis will invoice you for the full face value of the card i.e. for '
            . 'a £15 card, we\'ll invoice you £15. You will in turn charge your customer '
            . 'the full face value. Every 2 days, we will calculate your Agency '
            . 'Fees, raise a Credit Note and credit your account. This should be '
            . 'considered your "income" and you should declare the amount your received '
            . 'for Agancy Fees for tax and VAT purposes.'
                
            //'contentOptions' => [...],
            //'options' => [...],
        ],
        [
            'label' => 'I can\'t see my xbox leaflet properly.',
            'content' => '<p>If you are using Mozilla Firefox and you trying to print an Xbox Code but the leaflet is blurry, follow these steps:</p> '
            . '<ul>'
            . '<li>Open a new tab and navigate to <a href="https://get.adobe.com/uk/reader/">https://get.adobe.com/uk/reader/</a></li> '
            . '<li>Follow the steps on the website, and install the Reader.</li> '
            . '<li>When the installation process is done, go back to EDSR and refresh the page and try to print it.</li> '
            . '</ul>'
            . '<p>If your browser still opens the Xbox label with the default PDF Reader, follow these steps:</p> '
            . '<ul>'
            . '<li>On the top right corner of your browser, click on the "list" icon and select "Options"</li> '
            . '<li>When the new tab opens, select "applications" on the left menu.</li> '
            . '<li>You need to change all the "Adobe Acrobat" files to "Use Adobe Reader", this will make Adobe Reader the default PDF Viewer.</li> '
            . '</ul>'
            . '<p>If you still have issues, try to download the PDF once it is displayed and then open it with Adobe PDF Reader.</p>'
                
            //'contentOptions' => [...],
            //'options' => [...],
        ],
        [
            'label' => 'I can\'t see the "Shop"? / How do I buy keys?',
            'content' => '<p>We enable the shop on a Customer by Customer basis. '
                    . 'We also need to check that your account is properly set up. '
                    . 'That sometimes takes a day or so. If you think you should have'
                    . 'access to the shop and haven\'t, please contact esd@exertis.co.uk</p>'
                
            //'contentOptions' => [...],
            //'options' => [...],
        ],
        [
            'label' => 'I can\'t see the Xbox Gift Cards / a certain product in "Shop"?',
            'content' => '<p>Some products require prior approval by the publisher.'
                    . 'Xbox Gift Cards is one such product. '
                    . 'If you think you should have '
                    . 'access to a particular product and haven\'t, please contact esd@exertis.co.uk</p>'
                
            //'contentOptions' => [...],
            //'options' => [...],
        ],
        [
            'label' => 'How do I create a Microsoft Live account?',
            'content' => '<p>Please visit <a href="https://login.live.com/">https://login.live.com/</a> and click on "No account? Create one!"</p>`'
                
            //'contentOptions' => [...],
            //'options' => [...],
        ],
        

    ]

]);

?>